### ISSUE TITLE
Any specific reason for the incompatible pinout?

### ISSUE THREAD

**Issue by Miigon** [zhiayang/mikoto#9]
It seems like the current pinout of mikoto isn't really compatible with nice!nano or promicro-based keyboard pcb. The top most pins on the left and right side are EXT_5V and VDD_NRF instead of B- and B+, and VBAT is connected to where RAW would be on a pro micro. I wonder is this a deliberate design choice?

Because of the different battery pinout, mikoto can't really be used as a drop-in replacement for a nice!nano. Instead requiring the keyboard pcb to be specifically designed for and only for mikoto. (aka connecting battery to RAW). But that would render the keyboard incompatible with any other pro micro compatible microcontroller since most controllers connect VBUS to RAW, which meant they will SEND 5V DIRECTLY TO THE BATTERY if used on a pcb designed for mikoto.

(Unfortunately I have to find out about the incompatible pinout the hard way by distroying 2 of my mikoto boards (dead nrf52840) because the battery tried to send too high of a voltage to what it thought was B+ but actually is VDD_NRF. 😢)

**Comment by zhiayang** [comment]
I guess you @-ed me on discord because I didn't reply (sorry, didn't see). Anyway, putting my response from there here:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/500236/171456018-db56c1dd-d9ca-4ae7-bcb1-2812f4f9d405.png">

The nice!nano isn't really designed for the battery to be on the keyboard (in fact, v2 changed the B+/B- hole sizes so people wouldn't be confused). For the case of soldering battery leads directly to the board, there are two smaller holes (not on the edge, near the middle-top) that are meant for this. In this sense it is still a pro-micro and/or nice!nano drop-in.
